name: deploy-infra-services

on:
  push:
    branches:
      - infra
    paths:
      - "infra/k8s/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing CIVO cli
        uses: civo/action-civo
        with:
          token: ${{ secrets.CIVO_TOKEN }}
      - name: Save Civo kubeconfig
        run: civo kubernetes config ${{ secrets.CLUSTER_NAME }} --save
      - name: Deploying infrastructure services like ingress, secrets, darabases.
        run: kubectl create namespace nats-dev
          kubectl create -f ingress-srv.yaml -n nats-dev
          kubectl create secret generic jwt-secret --from-literal=JWT_KEY={{ secrets.JWT_KEY }} -n nats-dev
          kubectl apply -f auth-mongodb-depl.yaml -n nats-dev
          kubectl rollout status deployment/auth-mongo-depl -n nats-dev
          kubectl apply -f expiration-redis-depl.yaml -n nats-dev
          kubectl rollout status deployment/expiration-redis-depl -n nats-dev
          kubectl apply -f nats-depl.yaml -n nats-dev
          kubectl rollout status deployment/nats-depl -n nats-dev
          kubectl apply -f orders-mongodb-depl.yaml -n nats-dev
          kubectl rollout status deployment/orders-mongo-depl -n nats-dev
          kubectl apply -f payments-mongodb-depl.yaml -n nats-dev
          kubectl rollout status deployment/payments-mongo-depl -n nats-dev
          kubectl apply -f tickets-mongodb-depl.yaml -n nats-dev
          kubectl rollout status deployment/tickets-mongo-depl -n nats-dev
